"""create cnab tables

Revision ID: 96d9e7a430b0
Revises:
Create Date: 2026-04-02 20:29:15.084544
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96d9e7a430b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cnab_store",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("owner_name", sa.String(length=50), nullable=False),
        sa.Column("owner_cpf", sa.String(length=11), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("inactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "owner_cpf", name="uq_store_name_cpf"),
    )
    op.create_table(
        "cnab_transaction_type",
        sa.Column("code", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("nature", sa.String(length=10), nullable=False),
        sa.Column("sign", sa.String(length=1), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("inactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("code", name="uq_transaction_type_code"),
    )
    op.create_table(
        "cnab_transaction",
        sa.Column("transaction_type_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("card", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.Date(), nullable=False),
        sa.Column("occurred_time", sa.Time(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("inactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["cnab_store.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_type_id"],
            ["cnab_transaction_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_transaction_store_date", "cnab_transaction", ["store_id", "occurred_at"], unique=False)
    op.create_index("idx_transaction_upload", "cnab_transaction", ["upload_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_transaction_upload", table_name="cnab_transaction")
    op.drop_index("idx_transaction_store_date", table_name="cnab_transaction")
    op.drop_table("cnab_transaction")
    op.drop_table("cnab_transaction_type")
    op.drop_table("cnab_store")
    # ### end Alembic commands ###
